### ISSUE TITLE
Investigate use of Google Application Integration

### ISSUE THREAD

**Issue by nigelcharman** [EcoNet-NZ/inaturalist-to-cams#66]
See https://cloud.google.com/application-integration/docs/overview

**Comment by Bluo16** [comment]
This may be a more visual way to use in future rather than Python

**Comment by nigelcharman** [comment]
Not sure if this will be a goer. We gain a lot of value from pyinaturalist, e.g. rate limiting, date transformations so would really need to call pyinaturalist as a data source.
